=== malamalca/pures3/schemas/Hrup/splosniPodatkiSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": ["stavba"],
    "properties": {
        "stavba": {
            "type": "object",
            "required": ["naziv", "lokacija", "KO", "parcele", "klasifikacija"],
            
            "properties": {
                "naziv": {"type": "string"},
                "lokacija": {"type": "string"},
                "KO": {"type": "string"},
                "parcele": {"type": "array", "minItems": 1},
                "klasifikacija": {"type": "string"}
            }
        },
        "investitorji": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": ["naziv", "naslov"]
            }
        },
        "zunanjiHrup": {
            "type": "object",
            "properties": {
                "kazalciHrupa": {"enum": ["obmocje", "lastni"]},
                "obmocje": {"enum": ["I", "II", "III", "IV"]}
            }
        },
        "vodjaProjektiranja": {"type": "string"},
        "izdelovalec": {"type": "string"},
        "stevilkaElaborata": {"type": "string"},
        "datum": {"type": "string"}
    }
}

=== malamalca/pures3/projects/TestniProjekt/podatki/splosniPodatki.json
{
    "stavba": {
        "naziv": "Testni Projekt",
        "lokacija": "Mestna cesta 12",
        "KO": "Ljubljana",
        "parcele": [
            "123/4"
        ],
        "koordinate": {
            "X": 116215,
            "Y": 469925
        },
        "klasifikacija": "11100",
        "vrsta": "manjzahtevna",
        "notranjaTemp": 20
    },
    "investitorji": [
        {
            "naziv": "Janez Novak",
            "naslov": "Mestna cesta 12, 1000 Ljubljana"
        }
    ],
    "vodjaProjektiranja": "Franc Pavlin, udia, ZAPS 1122",
    "izdelovalec": "Franc Pavlin, udia, ZAPS 1122",
    "datum": "april 2023"
}
